### ISSUE TITLE
Proposal: Support time zone for `docker-logs`

### ISSUE THREAD

**Issue by boaz0** [docker/cli#604]
This is a follow up to #33778 and #35051.

Recap:
One of the requests is to see log timestamp according to a timezone, it was decided that it would be very risky to implement it on the server-side: https://github.com/moby/moby/pull/35051#issuecomment-334117784 and  https://notes.pault.ag/its-all-relative/.

Instead, it is preferable to implement an option in `docker container logs` that converts the UTC timestamp into a given timzeone one.

**Comment by popstas** [comment]
I am using script for replace datetime from UTC to server time, 
usage: `docker logs -t container_name | docker-logs-localtime`

https://gist.github.com/popstas/ffcf282492fd78389d1df2ab7f31052a

**Comment by jamiegau** [comment]
I am surprised this is not a bigger issue.  tracking docker logs against other logs is painful.  How hard could it be to get the logs to printout based on the container timezone.  That's not to hard to implement via environment variable etc..

**Comment by S474N** [comment]
Is there still no solution to this problem?

**Comment by anton-x-t** [comment]
> I am using script for replace datetime from UTC to server time, usage: `docker logs -t container_name | docker-logs-localtime`
> 
> https://gist.github.com/popstas/ffcf282492fd78389d1df2ab7f31052a

Still worked for me, it printed the time two times but that could easily be fixed.

https://gist.github.com/anton-x-t/859a69d0426ed1e4040660f57229c76c

**Comment by anton-x-t** [comment]
An forked version of @popstas Node script, with cleanup and timezone offset:
https://gist.github.com/anton-x-t/859a69d0426ed1e4040660f57229c76c

**Comment by anton-x-t** [comment]
Sure, but I don't want to and have the time to make the change, pull request, get it approved in docker/cli. This workaround will do until if the desired change is made. I'm not associated with Docker.

**Comment by RomanValov** [comment]
As a workaround one can switch between local and UTC timezones based on logging driver used (seems to be a bug):

https://github.com/moby/moby/issues/46910

**Comment by thaJeztah** [comment]
I think this is still something we're considering adding; not sure where the code would be best implemented, but let me reopen this one for the time being.

**Comment by thaJeztah** [comment]
@jirikrepl what version of Docker are you running? It may be that you're depending on a bug, which was fixed in https://github.com/moby/moby/pull/46913

**Comment by jirikrepl** [comment]
@thaJeztah I think I am using the latest docker version.
I think I have set time zones well in the container and on the host. 
But I still see logs in the UTC time.

```
$ docker version
Client: Docker Engine - Community
 Version:           27.0.1
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7fafd33
 Built:             Mon Jun 24 14:57:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       ff1e2c0
  Built:            Mon Jun 24 14:57:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


# date on the host
$ date
Wed Jun 26 18:39:31 CEST 2024

# date in the container
$ docker exec -it <my_container> bash
$ date
Wed Jun 26 18:40:27 CEST 2024
$ echo $TZ
Europe/Prague


# logs showing UTC time
$ docker logs -tf nedatluj
2024-06-26T16:41:23.730804303Z => Setting node version
2024-06-26T16:41:24.352243758Z NODE_VERSION=14.21.4
```
